### ISSUE TITLE
[Migrate]: Providing Support at the BuddyPress Forums

### ISSUE THREAD

**Issue by imath** [buddypress/bp-documentation#276]
### Link to the existing BP Codex page.

https://codex.buddypress.org/participate-and-contribute/providing-support-at-the-buddypress-forums/

### What needs to be done?

This is a very important page. We need to migrate it, but there's a lot of work to accomplish to make it fully useful:
- [x] Review links
- [x] Check forum moderators can achieve all the described capabilities
~Include a link to the documentation about the BP Site Health debug panels (doc to be created).~

### Handbook to migrate the page in

buddypress/docs/contributor

### Tasks to accomplish

- [x] This task has been added to the "Todo" panel of the Documentation project.
- [x] The corresponding line of the `data/README.md` Pages list has been marked as "Migrate issue/task created".
- [x] A PR has been submitted to the BuddyPress GH repository, it has been linked to this issue/task & the task was moved to the "In progress" panel of the Documentation project.
- [x] The PR has been converted to a SVN patch and committed to the BuddyPress SVN repository & the task was moved to the "Done"  panel of the Documentation project.
