### ISSUE TITLE
[Ignore]: Developer Resources

### ISSUE THREAD

**Issue by imath** [buddypress/bp-documentation#279]
### Link to the existing BP Codex page.

https://codex.buddypress.org/developer/

### Why should we ignore this page?

It's the developer doc introduction without any toc. Not needed imho.

### Tasks to accomplish

- [x] This task has been added to the "Todo" panel of the Documentation project.
- [ ] The corresponding line of the `data/README.md` Pages list has been marked as "Ignore issue/task created".
- [ ] One of the BuddyPress Core committer reviewed it and agreed to ignore this Codex page.
- [ ] The task was moved to the "Done" panel of the Documentation project.

**Comment by imath** [comment]
Ouch, this is a duplicate
