### ISSUE TITLE
[Add]: BuddyPress Site Health panel

### ISSUE THREAD

**Issue by imath** [buddypress/bp-documentation#4]
### What needs to be done?

A new Markdown file should be added into the `administration/tools` subdirectory to explain how to access this panel and what the informations that are listed can be useful to debug / troubleshoot or submit a support request.

<img width="1438" alt="site-heath-bp-panel" src="https://github.com/buddypress/bp-documentation/assets/1834524/a096e3b7-1ebf-4ac7-9b7b-5904ee4180a1">

#### Reference material

- [Site Health screen](https://wordpress.org/documentation/article/site-health-screen/#active-theme)

### Handbook to add the page in

buddypress/docs/user

### Tasks to accomplish

- [x] This task has been added to the "Todo" panel of the Documentation project.
- [x] A PR has been submitted to the BuddyPress GH repository, it has been linked to this issue/task & the task was moved to the "In progress" panel of the Documentation project.
- [x] The` user/README.md` was updated to contain a link to the page created by this task.
- [ ] The PR has been converted to a SVN patch and committed to the BuddyPress SVN repository & the task was moved to the "Done"  panel of the Documentation project.

**Comment by imath** [comment]
Another task to accomplish once this page will be created is to update 
`"markdown_source": "../contributor/support/README.md"` so that it includes a link to the page created here.
See #276

**Comment by emaralive** [comment]
Trac ticket [9237](https://buddypress.trac.wordpress.org/ticket/9237) was created to resolve an anomaly with the BuddyPress panel - Active components attribute.

**Comment by emaralive** [comment]
Trac ticket [9245](https://buddypress.trac.wordpress.org/ticket/9245) was created to resolve multiple issues with the BuddyPress Constants panel.
